session_name: cgreenpoint
start_directory: ~/projects/cgreenpoint/
windows:
  - window_name: app
    layout: main-vertical
    panes:
      - blank
      - blank
  - window_name: git
    panes:
      - lazygit
  - window_name: vim
    panes:
      - cvim
